name: Multi-Platform Build (STM32 & Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-pack:
    strategy:
      matrix:
        include:
          - preset: "stm32f411xe-debug"
            os: ubuntu-latest
          - preset: "win-debug"
            os: windows-latest
          - preset: "win-release"
            os: windows-latest
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache APT Packages (Linux)
      if: runner.os == 'Linux'
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/build.yaml') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install -y -q ninja-build gcc-arm-none-eabi

    - name: Set up MSVC Developer Command Prompt (Windows)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: cmake --preset ${{ matrix.preset }}

    - name: Build Firmware
      run: cmake --build --preset ${{ matrix.preset }} --parallel

    - name: Install and Organize SDK
      run: cmake --install build/${{ matrix.preset }} --prefix dist/${{ matrix.preset }} --component app

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ matrix.preset }}
        path: dist/${{ matrix.preset }}/
        if-no-files-found: error
